### ISSUE TITLE
E2EE for SMS /MMS (and even RCS)

### ISSUE THREAD

**Issue by ElsAr4e** [FossifyOrg/SMS-Messenger#27]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I would like to have the possibility like Silence or Deku to enable E2EE for SMS or MMS (and even RCS)? Maybe you can also use a qr code to enable the e2ee: https://github.com/deku-messaging/Deku-SMS-Android/issues/183

**Describe alternatives you've considered**
Until now I only know Silence (https://git.silence.dev/Silence/Silence-Android) or Deko SMS (https://github.com/deku-messaging/Deku-SMS-Android) for E2EE SMS or MMS

**Additional context**
Maybe you could have settings (opt-in) that messages without E2EE are not accepted / send an error message
Display a warning if the messages don't have E2EE (opt-in; like a red lock icon)

**Comment by Aga-C** [comment]
Isn't it too much for this app? What do you think @naveensingh?

**Comment by ikanakova** [comment]
I think RCS would be great and another E2EE would be unnecessary.

**Comment by ElsAr4e** [comment]
> I think RCS would be great and another E2EE would be unnecessary.

But if the other device does not have RCS it will be automatically converted into an SMS or MMS without E2EE? So you would have to prevent that?

**Comment by naveensingh** [comment]
Nope, too much and too soon.

As far as I know, there is still no API for RCS.

**Comment by moriel5** [comment]
Hmm... I remember that back in the day, CyanogenMod included E2EE SMS/MMS via WhisperPush.

I wonder whether it may be possible to make a common library for FOSS apps to include something similar. Perhaps the Silence devs could assist in that matter.

**Comment by inson1** [comment]
I think there shoulld be issue (with blocked label) o discussion about rcs

And E2EE is great, but its hard feature, so I'm for reopening and deleting the part about rcs

**Comment by jayb-g** [comment]
RCS support will be a great plus and more than required for an SMS app in the future.  
Of course the fallback will always be the plain old SMS

**Comment by moriel5** [comment]
@jayb-g I just read a bit more about RCS recently, and I am staying to understand why it is so hard to implement.

Past of the problem with RCS is that while it is technically a standard, the way it is ratified makes it's status as an open standard dubious, since it's not clear whether all the necessary details for implementing it are actually provided without a license from the GSM association, and in the current situation, the way that the existing solutions are implemented, makes it little better than iMessage in terms of standardization.

Personally, until someone with the know-how and capabilities steps up to clear the situation, I think that E2EE support is actually more practical, since the current solutions render RCS a huge privacy and closed garden risk.

**Comment by jayb-g** [comment]
> Part of the problem with RCS is that while it is technically a standard, the way it is ratified makes it's status as an open standard dubious

Agree

> I think that E2EE support is actually more practical,....

Not really. E2EE (even with just plaintext sms support)would need a whole lot of keysharing(and thus privacy issues?) mechanism and enc/dec in place and maybe also internet permissions for that which would make the app basically another chat App and not carrier SMS app.

> since the current solutions render RCS a huge privacy and closed garden risk.

Completely agree. But isn't RCS already an open standard? Although it doesn't have E2EE in built, but apps implementing RCS can. See specifications section in [wiki](https://en.wikipedia.org/wiki/Rich_Communication_Services)

**Comment by moriel5** [comment]
That is quite interesting, although I am sure that a compromise could be found (perhaps with decentralized key-sharing, though that in itself would take some creative thinking to both preserve privacy and security, and getting more people to easily use it).

Regarding the last part of your reply, the first part of my reply answers that.

**Comment by jayb-g** [comment]
Sure, but without different devices/operator/OSs/Apps following the same standard like RCS(our best best as of now), it would again lead to creation of a walled garden.

**Comment by moriel5** [comment]
That's the problem, that at this point, RCS is almost a walled garden itself at this point, where it is questionable if anyone who is not approved to set up an RCS server could do so, and almost everyone who has an RCS is closing theirs in favor of Google's.

So while RCS may potentially be the best bet, in it's current form it's almost the same situation as with iCloud, just with Google instead of Some.

Google has done a lot of work, but most of it was not to bring everyone together with RCS a standard (they tried doing that a little at the beginning), but rather to be a walled garden where they are the warden.

**Comment by jayb-g** [comment]
> Google has done a lot of work, but most of it was not to bring everyone together with RCS as a standard (they tried doing that a little at the beginning), but rather to be a walled garden where they are the warden.

Well, hard to say what their intent was/is but if RCS is moving towards a standard it really depends on the industry adoption whether it remains walled garden or not. (I believe non-Google RCS users can/should be able to communicate with each other)

**Comment by moriel5** [comment]
Originally, that is very probable, however they may have hit a roadblock not related to adoption that made them give up on open standards (and standardization in general, both of which mark a trend with Google lately abandoning with specific things).

If RCS was moving towards a standard, then I would have agreed with you, since I would be all for a proper standard that would also be as good or better than iMessage to be adopted, however it seems that RCS is currently heading in the opposite direction, especially with GSMA's outlining of the standard being as sketchy as it is.

I'm not saying to give up on RCS, but rather that we need people with proper understanding of both programming and law to unravel the mess that RCS currently is before we can even begin talking about supporting it.

There is a real reason why RCS doesn't have any FOSS support yet, and it's not for lack of interest, but rather lack of a foothold on how to support it.

**Comment by jayb-g** [comment]
> There is a real reason why RCS doesn't have any FOSS support yet, and it's not for lack of interest, but rather lack of a foothold

Hoping that would change soon.

**Comment by MulverineX** [comment]
In theory it would be possible to roll your own RCS implementation since the protocol is open source, but this would also require rolling an independent authoritative alternative to the Google Jibe service. That's just not something a hobby project like this has the resources to accomplish unless the team accepted a partnership with FUTO or something (this would be ideal).

Ideally Google would've made stock RCS w/ Jibe integration a system component with a rich API that any app can implement, but unfortunately, due to their close minded bullshit surrounding "spam prevention" (doesn't prevent any of it), they rely on Safety Net and their own ARR closed-source app.

**Comment by MulverineX** [comment]
@naveensingh I'm curious what your opinion would be on partnering with FUTO in a similar way to Immich, to accomplish the goal of bringing a more open RCS service to users?

**Comment by moriel5** [comment]
Partnership with FUTO for this would certainly be nice, at least for clearing up RCS's current sketchiness (the documentation is far from comprehensive about certain things, such as who even is allowed to roll their own server implementation, according to the GSMA's own rules).

**Comment by ElsAr4e** [comment]
As mentioned until now you can try Silence (https://git.silence.dev/Silence/Silence-Android) or Deko SMS (https://github.com/deku-messaging/Deku-SMS-Android)

Exodus shows 2 known trackers if you scan Deku SMS: https://reports.exodus-privacy.eu.org/en/reports/460028/

Or you use Messengers like SimpleX Chat (https://simplex.chat/)

**Comment by naveensingh** [comment]
Anything RCS/E2EE related is for the future. Nothing can be said now.

**Comment by MulverineX** [comment]
I'm not asking for a timeline or to have this feature soon, I was just curious whether you would be interested in a FUTO partnership?
